<?php

use Illuminate\Database\Seeder;

class CountryStateCitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Country list
        $country = [
            ['name' => 'Canada']
        ];

        foreach ($country as $row){
            $obj = new \App\Country();
            $obj->fill($row);
            $obj->save();
        }

        // State list
        $states = [
            ['name' => 'Alberta', 'country_id' => 1],
            ['name' => 'British Columbia', 'country_id' => 1],
            ['name' => 'Manitoba', 'country_id' => 1],
            ['name' => 'New Brunswick', 'country_id' => 1],
			['name' => 'Newfoundland and Labrador', 'country_id' => 1],
			['name' => 'Northwest Territories', 'country_id' => 1],
			['name' => 'Nova Scotia', 'country_id' => 1],
			['name' => 'Nunavut', 'country_id' => 1],
			['name' => 'Ontario', 'country_id' => 1],
			['name' => 'Prince Edward Island', 'country_id' => 1],
			['name' => 'Quebec', 'country_id' => 1],
			['name' => 'Saskatchewan', 'country_id' => 1],
			['name' => 'Yukon', 'country_id' => 1],
        ];

        foreach ($states as $row){
            $obj = new \App\State();
            $obj->fill($row);
            $obj->save();
        }

        // City list
        
		
		$cities = [
            ['name' => 'Airdrie', 'state_id' => 1],
			['name' => 'Beaumont', 'state_id' => 1],
			['name' => 'Brooks', 'state_id' => 1],
			['name' => 'Calgary', 'state_id' => 1],
			['name' => 'Camrose', 'state_id' => 1],
			['name' => 'Chestermere', 'state_id' => 1],
            ['name' => 'Cold Lake', 'state_id' => 1],
			['name' => 'Edmonton', 'state_id' => 1],
			['name' => 'Fort Saskatchewan', 'state_id' => 1],
			['name' => 'Grande Prairie', 'state_id' => 1],
			['name' => 'Lacombe', 'state_id' => 1],
			['name' => 'Leduc', 'state_id' => 1],
            ['name' => 'Lethbridge', 'state_id' => 1],
			['name' => 'Lloydminster', 'state_id' => 1],
			['name' => 'Medicine Hat', 'state_id' => 1],
			['name' => 'Red Deer', 'state_id' => 1],
			['name' => 'Spruce Grove', 'state_id' => 1],
			['name' => 'St. Albert', 'state_id' => 1],
            ['name' => 'Wetaskiwin', 'state_id' => 1],
			['name' => 'Abbotsford', 'state_id' => 2],
			['name' => 'Armstrong', 'state_id' => 2],
			['name' => 'Burnaby', 'state_id' => 2],
			['name' => 'Campbell River', 'state_id' => 2],
			['name' => 'Castlegar', 'state_id' => 2],
			['name' => 'Chilliwack', 'state_id' => 2],
			['name' => 'Colwood', 'state_id' => 2],
			['name' => 'Coquitlam', 'state_id' => 2],
			['name' => 'Courtenay', 'state_id' => 2],
			['name' => 'Cranbrook', 'state_id' => 2],
			['name' => 'Dawson Creek', 'state_id' => 2],
			['name' => 'Delta', 'state_id' => 2],
			['name' => 'Duncan', 'state_id' => 2],
			['name' => 'Enderby', 'state_id' => 2],
			['name' => 'Fernie', 'state_id' => 2],
			['name' => 'Fort St. John', 'state_id' => 2],
			['name' => 'Grand Forks', 'state_id' => 2],
			['name' => 'Greenwood', 'state_id' => 2],
			['name' => 'Kamloops', 'state_id' => 2],
			['name' => 'Kelowna', 'state_id' => 2],
			['name' => 'Kimberley', 'state_id' => 2],
			['name' => 'Langford', 'state_id' => 2],
			['name' => 'Langley', 'state_id' => 2],
			['name' => 'Maple Ridge', 'state_id' => 2],
			['name' => 'Merritt', 'state_id' => 2],
			['name' => 'Nanaimo', 'state_id' => 2],
			['name' => 'Nelson', 'state_id' => 2],
			['name' => 'New Westminster', 'state_id' => 2],
			['name' => 'North Vancouver', 'state_id' => 2],
			['name' => 'Parksville', 'state_id' => 2],
			['name' => 'Penticton', 'state_id' => 2],
			['name' => 'Pitt Meadows', 'state_id' => 2],
			['name' => 'Port Alberni', 'state_id' => 2],
			['name' => 'Port Coquitlam', 'state_id' => 2],
			['name' => 'Port Moody', 'state_id' => 2],
			['name' => 'Powell River', 'state_id' => 2],
			['name' => 'Prince George', 'state_id' => 2],
			['name' => 'Prince Rupert', 'state_id' => 2],
			['name' => 'Quesnel', 'state_id' => 2],
			['name' => 'Revelstoke', 'state_id' => 2],
			['name' => 'Richmond', 'state_id' => 2],
			['name' => 'Rossland', 'state_id' => 2],
			['name' => 'Salmon Arm', 'state_id' => 2],
			['name' => 'Surrey', 'state_id' => 2],
			['name' => 'Terrace', 'state_id' => 2],
			['name' => 'Trail', 'state_id' => 2],
			['name' => 'Vancouver', 'state_id' => 2],
			['name' => 'Vernon', 'state_id' => 2],
			['name' => 'Victoria', 'state_id' => 2],
			['name' => 'West Kelowna', 'state_id' => 2],
			['name' => 'White Rock', 'state_id' => 2],
			['name' => 'Williams Lake', 'state_id' => 2],
			['name' => 'Brandon', 'state_id' => 3],
			['name' => 'Dauphin', 'state_id' => 3],
			['name' => 'Flin Flon', 'state_id' => 3],
			['name' => 'Morden', 'state_id' => 3],
			['name' => 'Portage la Prairie', 'state_id' => 3],
			['name' => 'Selkirk', 'state_id' => 3],
			['name' => 'Steinbach', 'state_id' => 3],
			['name' => 'Thompson', 'state_id' => 3],
			['name' => 'Winkler', 'state_id' => 3],
			['name' => 'Winnipeg', 'state_id' => 3],
			['name' => 'Bathurst', 'state_id' => 4],
			['name' => 'Campbellton', 'state_id' => 4],
			['name' => 'Dieppe', 'state_id' => 4],
			['name' => 'Edmundston', 'state_id' => 4],
			['name' => 'Fredericton', 'state_id' => 4],
			['name' => 'Miramichi', 'state_id' => 4],
			['name' => 'Moncton', 'state_id' => 4],
			['name' => 'Saint John', 'state_id' => 4],
			['name' => 'Corner Brook', 'state_id' => 5],
			['name' => 'Mount Pearl', 'state_id' => 5],
			['name' => 'St. Johns', 'state_id' => 5],
			['name' => 'Yellowknife', 'state_id' => 6],
			['name' => 'Halifax', 'state_id' => 7],
			['name' => 'Sydney', 'state_id' => 7],
			['name' => 'Dartmouth', 'state_id' => 7],
			['name' => 'Iqaluit', 'state_id' => 8],
			['name' => 'Barrie', 'state_id' => 9],
			['name' => 'Belleville', 'state_id' => 9],
			['name' => 'Brampton', 'state_id' => 9],
			['name' => 'Brant', 'state_id' => 9],
			['name' => 'Brantford', 'state_id' => 9],
			['name' => 'Brockville', 'state_id' => 9],
			['name' => 'Burlington', 'state_id' => 9],
			['name' => 'Cambridge', 'state_id' => 9],
			['name' => 'Clarence-Rockland', 'state_id' => 9],
			['name' => 'Cornwall', 'state_id' => 9],
			['name' => 'Dryden', 'state_id' => 9],
			['name' => 'Elliot', 'state_id' => 9],
			['name' => 'Greater Sudbury', 'state_id' => 9],
			['name' => 'Guelph', 'state_id' => 9],
			['name' => 'Haldimand County', 'state_id' => 9],
			['name' => 'Hamilton', 'state_id' => 9],
			['name' => 'Kawartha Lakes', 'state_id' => 9],
			['name' => 'Kenora', 'state_id' => 9],
			['name' => 'Kingston', 'state_id' => 9],
			['name' => 'Kitchener', 'state_id' => 9],
			['name' => 'London', 'state_id' => 9],
			['name' => 'Markham', 'state_id' => 9],
			['name' => 'Mississauga', 'state_id' => 9],
			['name' => 'Niagara Falls', 'state_id' => 9],
			['name' => 'Norfolk County', 'state_id' => 9],
			['name' => 'North Bay', 'state_id' => 9],
			['name' => 'Orillia', 'state_id' => 9],
			['name' => 'Oshawa', 'state_id' => 9],
			['name' => 'Ottawa', 'state_id' => 9],
			['name' => 'Owen Sound', 'state_id' => 9],
			['name' => 'Pembroke', 'state_id' => 9],
			['name' => 'Peterborough', 'state_id' => 9],
			['name' => 'Pickering', 'state_id' => 9],
			['name' => 'Port Colborne', 'state_id' => 9],
			['name' => 'Prince Edward County', 'state_id' => 9],
			['name' => 'Quinte West', 'state_id' => 9],
			['name' => 'Richmond Hill', 'state_id' => 9],
			['name' => 'Sarnia', 'state_id' => 9],
			['name' => 'Sault Ste. Marie', 'state_id' => 9],
			['name' => 'St. Catharines', 'state_id' => 9],
			['name' => 'St. Thomas', 'state_id' => 9],
			['name' => 'Stratford', 'state_id' => 9],
			['name' => 'Temiskaming Shores', 'state_id' => 9],
			['name' => 'Thorold', 'state_id' => 9],
			['name' => 'Thunder Bay', 'state_id' => 9],
			['name' => 'Timmins', 'state_id' => 9],
			['name' => 'Toronto', 'state_id' => 9],
			['name' => 'Vaughan', 'state_id' => 9],
			['name' => 'Waterloo', 'state_id' => 9],
			['name' => 'Welland', 'state_id' => 9],
			['name' => 'Windsor', 'state_id' => 9],
			['name' => 'Woodstock', 'state_id' => 9],
			['name' => 'Charlottetown', 'state_id' => 10],
			['name' => 'Summerside', 'state_id' => 10],
			["name" => "Alma", "state_id" => 11],
			["name" => "Amos", "state_id" => 11],
			["name" => "Amqui", "state_id" => 11],
			["name" => "Asbestos", "state_id" => 11],
			["name" => "Baie-Comeau", "state_id" => 11],
			["name" => "Baie-D'Urfé", "state_id" => 11],
			["name" => "Baie-Saint-Paul", "state_id" => 11],
			["name" => "Barkmere", "state_id" => 11],
			["name" => "Beaconsfield", "state_id" => 11],
			["name" => "Beauceville", "state_id" => 11],
			["name" => "Beauharnois", "state_id" => 11],
			["name" => "Beaupré", "state_id" => 11],
			["name" => "Bécancour", "state_id" => 11],
			["name" => "Bedford", "state_id" => 11],
			["name" => "Belleterre", "state_id" => 11],
			["name" => "Beloeil", "state_id" => 11],
			["name" => "Berthierville", "state_id" => 11],
			["name" => "Blainville", "state_id" => 11],
			["name" => "Boisbriand", "state_id" => 11],
			["name" => "Bois-des-Filion", "state_id" => 11],
			["name" => "Bonaventure", "state_id" => 11],
			["name" => "Boucherville", "state_id" => 11],
			["name" => "Lac-Brome", "state_id" => 11],
			["name" => "Bromont", "state_id" => 11],
			["name" => "Brossard", "state_id" => 11],
			["name" => "Brownsburg-Chatham", "state_id" => 11],
			["name" => "Candiac", "state_id" => 11],
			["name" => "Cap-Chat", "state_id" => 11],
			["name" => "Cap-Santé", "state_id" => 11],
			["name" => "Carignan", "state_id" => 11],
			["name" => "Carleton-sur-Mer", "state_id" => 11],
			["name" => "Causapscal", "state_id" => 11],
			["name" => "Chambly", "state_id" => 11],
			["name" => "Chandler", "state_id" => 11],
			["name" => "Chapais", "state_id" => 11],
			["name" => "Charlemagne", "state_id" => 11],
			["name" => "Châteauguay", "state_id" => 11],
			["name" => "Château-Richer", "state_id" => 11],
			["name" => "Chibougamau", "state_id" => 11],
			["name" => "Clermont", "state_id" => 11],
			["name" => "Coaticook", "state_id" => 11],
			["name" => "Contrecoeur", "state_id" => 11],
			["name" => "Cookshire-Eaton", "state_id" => 11],
			["name" => "Côte Saint-Luc", "state_id" => 11],
			["name" => "Coteau-du-Lac", "state_id" => 11],
			["name" => "Cowansville", "state_id" => 11],
			["name" => "Danville", "state_id" => 11],
			["name" => "Daveluyville", "state_id" => 11],
			["name" => "Dégelis", "state_id" => 11],
			["name" => "Delson", "state_id" => 11],
			["name" => "Desbiens", "state_id" => 11],
			["name" => "Deux-Montagnes", "state_id" => 11],
			["name" => "Disraeli", "state_id" => 11],
			["name" => "Dolbeau-Mistassini", "state_id" => 11],
			["name" => "Dollard-des-Ormeaux", "state_id" => 11],
			["name" => "Donnacona", "state_id" => 11],
			["name" => "Dorval", "state_id" => 11],
			["name" => "Drummondville", "state_id" => 11],
			["name" => "Dunham", "state_id" => 11],
			["name" => "Duparquet", "state_id" => 11],
			["name" => "East Angus", "state_id" => 11],
			["name" => "Estérel", "state_id" => 11],
			["name" => "Farnham", "state_id" => 11],
			["name" => "Fermont", "state_id" => 11],
			["name" => "Forestville", "state_id" => 11],
			["name" => "Fossambault-sur-le-Lac", "state_id" => 11],
			["name" => "Gaspé", "state_id" => 11],
			["name" => "Gatineau", "state_id" => 11],
			["name" => "Gracefield", "state_id" => 11],
			["name" => "Granby", "state_id" => 11],
			["name" => "Grande-Rivière", "state_id" => 11],
			["name" => "Hampstead", "state_id" => 11],
			["name" => "Hudson", "state_id" => 11],
			["name" => "Huntingdon", "state_id" => 11],
			["name" => "Joliette", "state_id" => 11],
			["name" => "Kingsey Falls", "state_id" => 11],
			["name" => "Kirkland", "state_id" => 11],
			["name" => "La Malbaie", "state_id" => 11],
			["name" => "La Pocatière", "state_id" => 11],
			["name" => "La Prairie", "state_id" => 11],
			["name" => "La Sarre", "state_id" => 11],
			["name" => "La Tuque", "state_id" => 11],
			["name" => "Lac-Delage", "state_id" => 11],
			["name" => "Lachute", "state_id" => 11],
			["name" => "Lac-Mégantic", "state_id" => 11],
			["name" => "Lac-Saint-Joseph", "state_id" => 11],
			["name" => "Lac-Sergent", "state_id" => 11],
			["name" => "L'Ancienne-Lorette", "state_id" => 11],
			["name" => "L'Assomption", "state_id" => 11],
			["name" => "Laval", "state_id" => 11],
			["name" => "Lavaltrie", "state_id" => 11],
			["name" => "Lebel-sur-Quévillon", "state_id" => 11],
			["name" => "L'Épiphanie", "state_id" => 11],
			["name" => "Léry", "state_id" => 11],
			["name" => "Lévis", "state_id" => 11],
			["name" => "L'Île-Cadieux", "state_id" => 11],
			["name" => "L'Île-Dorval", "state_id" => 11],
			["name" => "L'Île-Perrot", "state_id" => 11],
			["name" => "Longueuil", "state_id" => 11],
			["name" => "Lorraine", "state_id" => 11],
			["name" => "Louiseville", "state_id" => 11],
			["name" => "Macamic", "state_id" => 11],
			["name" => "Magog", "state_id" => 11],
			["name" => "Malartic", "state_id" => 11],
			["name" => "Maniwaki", "state_id" => 11],
			["name" => "Marieville", "state_id" => 11],
			["name" => "Mascouche", "state_id" => 11],
			["name" => "Matagami", "state_id" => 11],
			["name" => "Matane", "state_id" => 11],
			["name" => "Mercier", "state_id" => 11],
			["name" => "Métabetchouan–Lac-à-la-Croix", "state_id" => 11],
			["name" => "Métis-sur-Mer", "state_id" => 11],
			["name" => "Mirabel", "state_id" => 11],
			["name" => "Mont-Joli", "state_id" => 11],
			["name" => "Mont-Laurier", "state_id" => 11],
			["name" => "Montmagny", "state_id" => 11],
			["name" => "Montreal", "state_id" => 11],
			["name" => "Montreal West", "state_id" => 11],
			["name" => "Montréal-Est", "state_id" => 11],
			["name" => "Mont-Saint-Hilaire", "state_id" => 11],
			["name" => "Mont-Tremblant", "state_id" => 11],
			["name" => "Mount Royal", "state_id" => 11],
			["name" => "Murdochville", "state_id" => 11],
			["name" => "Neuville", "state_id" => 11],
			["name" => "New Richmond", "state_id" => 11],
			["name" => "Nicolet", "state_id" => 11],
			["name" => "Normandin", "state_id" => 11],
			["name" => "Notre-Dame-de-l'Île-Perrot", "state_id" => 11],
			["name" => "Notre-Dame-des-Prairies", "state_id" => 11],
			["name" => "Otterburn Park", "state_id" => 11],
			["name" => "Paspébiac", "state_id" => 11],
			["name" => "Percé", "state_id" => 11],
			["name" => "Pincourt", "state_id" => 11],
			["name" => "Plessisville", "state_id" => 11],
			["name" => "Pohénégamook", "state_id" => 11],
			["name" => "Pointe-Claire", "state_id" => 11],
			["name" => "Pont-Rouge", "state_id" => 11],
			["name" => "Port-Cartier", "state_id" => 11],
			["name" => "Portneuf", "state_id" => 11],
			["name" => "Prévost", "state_id" => 11],
			["name" => "Princeville", "state_id" => 11],
			["name" => "Québec", "state_id" => 11],
			["name" => "Repentigny", "state_id" => 11],
			["name" => "Richelieu", "state_id" => 11],
			["name" => "Richmond", "state_id" => 11],
			["name" => "Rigaud", "state_id" => 11],
			["name" => "Rimouski", "state_id" => 11],
			["name" => "Rivière-du-Loup", "state_id" => 11],
			["name" => "Rivière-Rouge", "state_id" => 11],
			["name" => "Roberval", "state_id" => 11],
			["name" => "Rosemère", "state_id" => 11],
			["name" => "Rouyn-Noranda", "state_id" => 11],
			["name" => "Saguenay", "state_id" => 11],
			["name" => "Saint-Augustin-de-Desmaures", "state_id" => 11],
			["name" => "Saint-Basile", "state_id" => 11],
			["name" => "Saint-Basile-le-Grand", "state_id" => 11],
			["name" => "Saint-Bruno-de-Montarville", "state_id" => 11],
			["name" => "Saint-Césaire", "state_id" => 11],
			["name" => "Saint-Colomban", "state_id" => 11],
			["name" => "Saint-Constant", "state_id" => 11],
			["name" => "Sainte-Adèle", "state_id" => 11],
			["name" => "Sainte-Agathe-des-Monts", "state_id" => 11],
			["name" => "Sainte-Anne-de-Beaupré", "state_id" => 11],
			["name" => "Sainte-Anne-de-Bellevue", "state_id" => 11],
			["name" => "Sainte-Anne-des-Monts", "state_id" => 11],
			["name" => "Sainte-Anne-des-Plaines", "state_id" => 11],
			["name" => "Sainte-Catherine", "state_id" => 11],
			["name" => "Sainte-Catherine-de-la-Jacques-Cartier", "state_id" => 11],
			["name" => "Sainte-Julie", "state_id" => 11],
			["name" => "Sainte-Marguerite-du-Lac-Masson", "state_id" => 11],
			["name" => "Sainte-Marie", "state_id" => 11],
			["name" => "Sainte-Marthe-sur-le-Lac", "state_id" => 11],
			["name" => "Sainte-Thérèse", "state_id" => 11],
			["name" => "Saint-Eustache", "state_id" => 11],
			["name" => "Saint-Félicien", "state_id" => 11],
			["name" => "Saint-Gabriel", "state_id" => 11],
			["name" => "Saint-Georges", "state_id" => 11],
			["name" => "Saint-Hyacinthe", "state_id" => 11],
			["name" => "Saint-Jean-sur-Richelieu", "state_id" => 11],
			["name" => "Saint-Jérôme", "state_id" => 11],
			["name" => "Saint-Joseph-de-Beauce", "state_id" => 11],
			["name" => "Saint-Joseph-de-Sorel", "state_id" => 11],
			["name" => "Saint-Lambert", "state_id" => 11],
			["name" => "Saint-Lazare", "state_id" => 11],
			["name" => "Saint-Lin-Laurentides", "state_id" => 11],
			["name" => "Saint-Marc-des-Carrières", "state_id" => 11],
			["name" => "Saint-Ours", "state_id" => 11],
			["name" => "Saint-Pamphile", "state_id" => 11],
			["name" => "Saint-Pascal", "state_id" => 11],
			["name" => "Saint-Pie", "state_id" => 11],
			["name" => "Saint-Raymond", "state_id" => 11],
			["name" => "Saint-Rémi", "state_id" => 11],
			["name" => "Saint-Sauveur", "state_id" => 11],
			["name" => "Saint-Tite", "state_id" => 11],
			["name" => "Salaberry-de-Valleyfield", "state_id" => 11],
			["name" => "Schefferville", "state_id" => 11],
			["name" => "Scotstown", "state_id" => 11],
			["name" => "Senneterre", "state_id" => 11],
			["name" => "Sept-Îles", "state_id" => 11],
			["name" => "Shawinigan", "state_id" => 11],
			["name" => "Sherbrooke", "state_id" => 11],
			["name" => "Sorel-Tracy", "state_id" => 11],
			["name" => "Stanstead", "state_id" => 11],
			["name" => "Sutton", "state_id" => 11],
			["name" => "Témiscaming", "state_id" => 11],
			["name" => "Témiscouata-sur-le-Lac", "state_id" => 11],
			["name" => "Terrebonne", "state_id" => 11],
			["name" => "Thetford Mines", "state_id" => 11],
			["name" => "Thurso", "state_id" => 11],
			["name" => "Trois-Pistoles", "state_id" => 11],
			["name" => "Trois-Rivières", "state_id" => 11],
			["name" => "Valcourt", "state_id" => 11],
			["name" => "Val-d'Or", "state_id" => 11],
			["name" => "Varennes", "state_id" => 11],
			["name" => "Vaudreuil-Dorion", "state_id" => 11],
			["name" => "Victoriaville", "state_id" => 11],
			["name" => "Ville-Marie", "state_id" => 11],
			["name" => "Warwick", "state_id" => 11],
			["name" => "Waterloo", "state_id" => 11],
			["name" => "Waterville", "state_id" => 11],
			["name" => "Westmount", "state_id" => 11],
			["name" => "Windsor", "state_id" => 11],
			['name' => 'Estevan', 'state_id' => 12],
			['name' => 'Fort QuAppelle', 'state_id' => 12],
			['name' => 'Humboldt', 'state_id' => 12],
			['name' => 'Ille-A-La-Crosse', 'state_id' => 12],
			['name' => 'Kindersley', 'state_id' => 12],
			['name' => 'La Ronge', 'state_id' => 12],
			['name' => 'Lloydminster', 'state_id' => 12],
			['name' => 'Meadow Lake', 'state_id' => 12],
			['name' => 'Melfort', 'state_id' => 12],
			['name' => 'Moose Jaw', 'state_id' => 12],
			['name' => 'Nipawin', 'state_id' => 12],			
			['name' => 'North Battleford', 'state_id' => 12],
			['name' => 'Prince Albert', 'state_id' => 12],
			['name' => 'Regina', 'state_id' => 12],
			['name' => 'Saskatoon', 'state_id' => 12],
			['name' => 'Swift Current', 'state_id' => 12],
			['name' => 'Weyburn', 'state_id' => 12],
			['name' => 'Yorkton', 'state_id' => 12],
			['name' => 'Whitehorse', 'state_id' => 13],
		];	

        foreach ($cities as $row){
            $obj = new \App\City();
            $obj->fill($row);
            $obj->save();
        }
    }
}
